INSERT INTO TODOS (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1001, 'mark', 'Learn AWS Now', CURRENT_DATE, false);

INSERT INTO TODOS (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1002, 'mark', 'Learn GCP Now', CURRENT_DATE, false);

INSERT INTO TODOS (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1003, 'mark', 'Learn Kotlin Now', CURRENT_DATE, false);

INSERT INTO TODOS (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1004, 'mark', 'Learn Java Fullstack Now', CURRENT_DATE, false);

INSERT INTO TODOS (ID, USERNAME, DESCRIPTION, TARGET_DATE, DONE)
VALUES (1005, 'mark', 'Learn Docker Now', CURRENT_DATE, false);
